//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VT_Articulo()
        {
            this.VT_Orden = new HashSet<VT_Orden>();
        }
    
        public int id { get; set; }
        public int idTipoArticulo { get; set; }
        public int idGenero { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public int existencia { get; set; }
        public int estado { get; set; }
    
        public virtual VT_Genero VT_Genero { get; set; }
        public virtual VT_TipoArticulo VT_TipoArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VT_Orden> VT_Orden { get; set; }
    }
}
