//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ventas_ONLINEEntities : DbContext
    {
        public Ventas_ONLINEEntities()
            : base("name=Ventas_ONLINEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VT_Articulo> VT_Articulo { get; set; }
        public virtual DbSet<VT_Genero> VT_Genero { get; set; }
        public virtual DbSet<VT_Orden> VT_Orden { get; set; }
        public virtual DbSet<VT_Perfil> VT_Perfil { get; set; }
        public virtual DbSet<VT_TipoArticulo> VT_TipoArticulo { get; set; }
        public virtual DbSet<VT_TipoPerfil> VT_TipoPerfil { get; set; }
        public virtual DbSet<VT_Usuario> VT_Usuario { get; set; }
    }
}
